services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.adams
      args:
        VITE_API_URL: https://staging.backend.neighshopglobal.com
    container_name: test-staging-frontend
    restart: unless-stopped
    ports:
    - 127.0.0.1:20000:80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.adams
    container_name: test-staging-backend
    restart: unless-stopped
    ports:
    - 127.0.0.1:20001:8000
